# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

consumer_key: "UBoRarVKbOWoyyxsCguDH3Peh"
consumer_secret: "DgTaipZ9LtC6NHcRGyLPdY9XZPqIqbaRkOCAWt7vkSLalE4JJZ"
access_token: "705501940134879232-8UHRimrEy0v99fGdof5nyA7ZAWuTRDB"
access_secret: "RcvIBzkTqk3oTkoJfuz4f0GpF5b0oUgYq1lrNIMxmdKOj"
