# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

consumer_key: "G62xnlry4nRWOcsPIUHLjb2D8"
consumer_secret: "uetkQYwhWCsvb33OfRKEwdf98IPIdBXn222DxEV2TEYahUMRAO"
access_token: "705501940134879232-kXQeZxUO3x2EBt4kXAGNtnwgIPDYZqT"
access_secret: "YHPAYVDCxWunEteFudiYQ7dYp4cPwZjmz1bvdJwu4Nksl"
